spring:
  application:
    name: spring-lotto
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:database
