spring:
  application:
    name: spring-lotto
  config:
    activate:
      on-profile: dev
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lotto-mysql:3306/lotto?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: lotto
    password: 4321


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
        exclude: threaddump, heapdump

toss:
  client:
    api-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    payment-url: /v1/payments/confirm
jwt:
  access-token-expiry: 16000000
  secret: justkeyfortestkeyisThisKeyWithOverall256bits

loki:
  url: http://lotto-loki:3100/loki/api/v1/push
