spring:
  application:
    name: spring-lotto
  data:
    redis:
      host: lotto-redis
      port: 6379

  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:database

  h2:
    console:
      enabled: true


toss:
  client:
    api-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    payment-url: /v1/payments/confirm
    cancel-url: /v1/payments/{paymentKey}/cancel

cors:
  allowed-origins: http://localhost:3000

jwt:
  access-token-expiry: 160000000000
  secret: justkeyfortestkeyisThisKeyWithOverall256bits
server:
  port: 8085
