version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-lotto
    environment:
      MYSQL_ROOT_PASSWORD: 4321
      MYSQL_DATABASE: lotto
      MYSQL_USER: lotto
      MYSQL_PASSWORD: 4321
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/scripts/lotto_init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --general_log=1 
      --general_log_file=/var/log/mysql/general.log
      --slow_query_log=1 
      --slow_query_log_file=/var/log/mysql/slow.log
      --long_query_time=1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p4321 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/config.yml


  spring-lotto:
    build:
      context: ../
    container_name: spring-lotto
    ports:
      - "8080:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#          memory: 4g
    depends_on:  # Spring 애플리케이션 시작 순서 지정
      mysql:
        condition: service_healthy
    volumes:
      - ../build/libs/spring-lotto-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      SPRING_PROFILES_ACTIVE: dev

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: example-org
      DOCKER_INFLUXDB_INIT_BUCKET: k6-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: adminToken1234
    command:
      - influxd

  prom:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prom:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links:
      - spring-lotto
      - influxdb

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3500:3000"
  front-lotto:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: front-lotto
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - spring-lotto

    networks:
      - app-network

volumes:
  grafana:
  prom:
  influxdb:
  mysql-data:
  loki-data:
