apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://lotto-loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://lotto-influx:8086
    jsonData:
      version: Flux
      organization: dev-org
      defaultBucket: lotto-bucket
      tlsSkipVerify: true
    secureJsonData:
      token: adminToken1234


  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://lotto-prometheus:9090
    basicAuth: false
    isDefault: false
    editable: false

  - name: MySQL
    type: mysql
    access: proxy
    orgId: 1
    url: lotto-mysql:3306
    user: lotto
    secureJsonData:
      password: "4321"
    jsonData:
      database: lotto
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: false
    editable: true
    version: 1
