server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lotto-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mysql_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: mysql
          __path__: /var/log/mysql/general.log
