server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lotto-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mysql_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: mysql
          __path__: /var/log/mysql/general.log

    pipeline_stages:
      - regex:
          expression: ^(?P<ts>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z)\s+(?P<thread>\d+)\s+Query\s+(?P<query>.+)$
      - labels:
          thread: ""
          ts: ""
          query: ""

      - regex:
          expression: ^(?P<type>select|update|delete|insert)\b
          source: query
      - labels:
          type: ""
