SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM lotto;
DELETE FROM lotto_round_info;
DELETE FROM lotto_publish;
DELETE FROM lotto_statistics;
DELETE FROM orders;
DELETE FROM members;
DELETE FROM purchase;
DELETE FROM purchase_info;
SET FOREIGN_KEY_CHECKS = 1;
